jump_servers:
- host: 192.168.50.200
  password: student
  port: 22
  username: student
  
- host: 192.168.50.201
  password: student
  port: 22
  username: student

target:
  host: 192.168.50.202
  password: student
  port: 22
  username: student
